name: Download Process
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Download and Upload
      run: |
        mkdir download
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        driver=`git log --pretty=format: -1 --name-only *.md`
        export driver
        cd ..
        wget `cat $wiki/$driver | xargs` --directory-prefix=download
        pip install -r requirements.txt
        python upload.py
      env: 
        nutstore_url: ${{ secrets.nutstore_url }}
        nutstore_username: ${{ secrets.nutstore_username }}
        nutstore_password: ${{ secrets.nutstore_password }}
        box_url: ${{ secrets.box_url }}
        box_username: ${{ secrets.box_username }}
        box_password: ${{ secrets.box_password }}
        yandex_url: ${{ secrets.yandex_url }}
        yandex_username: ${{ secrets.yandex_username }}
        yandex_password: ${{ secrets.yandex_password }}

